FROM maven:3.9-eclipse-temurin-27 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:27-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 10000

ENV PORT=10000

CMD ["sh", "-c", "java -jar app.jar --server.port=${PORT:10000} --server.address=0.0.0.0"]